# Generated by Django 4.0.3 on 2022-03-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
